apiVersion: v1 
kind: Service
metadata: 
  name: frontend
  labels:
    app: frontend
spec: 
   type: LoadBalancer
   ports: 
    - protocol: TCP
      port: 3000
   selector:     
    app: frontend
---
apiVersion: v1 
kind: Service
metadata: 
  name: database
  labels:
    app: bc-15
spec: 
   ports: 
    - protocol: TCP
      port: 5432
   selector:     
    app: bc-15
---
apiVersion: v1 
kind: Service
metadata: 
  name: backend
  labels:
    app: bc-15
spec: 
   type: LoadBalancer
   ports: 
    - protocol: TCP
      port: 8080
   selector:     
    app: bc-15